server:
  port: 8090

retry:
  maxAttempts: 4
  delay: 1000

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:monline
    username: transfer
    password: password
    driverClassName: org.h2.Driver
db:
  schema: currency_service

currencies:
  main: RUB