server:
  port: 8090

retry:
  maxAttempts:  ${RETRY_MAX_ATTEMPTS:4}
  delay:  ${RETRY_DELAY:1000}

spring:
  h2:
    console.enabled:  ${H2_CONSOLE_ENABLED:true}
  datasource:
    url:  ${DATASOURCE_URL:jdbc:h2:mem:monline}
    username: ${DATASOURCE_USERNAME:transfer}
    password: ${DATASOURCE_PASSWORD:password}
    driverClassName: ${DATASOURCE_DRIVER:org.h2.Driver}
db:
  schema: ${DATASOURCE_SCHEMA:currency_service}

currencies:
  main: ${CURRENCIES_MAIN:RUB}