server:
  port: 8090

retry:
  maxAttempts:  ${RETRY_MAX_ATTEMPTS:4}
  delay:  ${RETRY_DELAY:1000}

spring:
  application:
    name: currency-service
  h2:
    console.enabled:  ${H2_CONSOLE_ENABLED:true}
  datasource:
    url:  ${DATASOURCE_URL:jdbc:h2:mem:monline}
    username: ${DATASOURCE_USERNAME:transfer}
    password: ${DATASOURCE_PASSWORD:password}
    driverClassName: ${DATASOURCE_DRIVER:org.h2.Driver}
db:
  schema: ${DATASOURCE_SCHEMA:currency_service}

currencies:
  main: ${CURRENCIES_MAIN:RUB}

managed:
  endpoints:
    enabled-by-default: ${MANAGED_ENDPOINTS_ENABLED_BY_DEFAULT:true}
    info:
      enabled: ${MANAGED_ENDPOINTS_INFO_ENABLED:true}


info:
  application:
    name: currency-service
    description: Currency service of Bank Online
    version: 1.0