server:
  port: 8081
  error:
    whitelabel:
      enabled: false

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:monline
    username: transfer
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

services:
  currencyService:
    host: http://localhost:8090
    getCurreniesPath: /currency/available
    convertPath: /rate/convert
    getCourcePath: /rate/${currencyCode}
