server:
  port: 8081
  error:
    whitelabel:
      enabled: false

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      client-id: mts1
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:monline
    username: transfer
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

services:
  currencyService:
    host: http://localhost:8090
    getCurreniesPath: /currency/available
    convertPath: /rate/convert
    getCourcePath: /rate/${currencyCode}
