spring:
  application:
    name: web-app
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_CONSUMER_BOOTSTRAP_SERVICE:localhost:29092}
      group-id: ${KAFKA_CONSUMER_GROUP_ID:transferGroup}
      auto-offset-reset: ${KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  profiles:
    active: ${WEB_SERVICE_PROFILE:prod}
  h2:
    console.enabled: true
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:monline}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASS:password}
    driverClassName: ${DATASOURCE_DRIVER:org.h2.Driver}
  jpa:
    spring.jpa.database-platform: ${JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate.ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate.format_sql: true

user:
  file:
    path: ${USER_FILE_PATH:src/main/resources/users/user-data.text}

server:
  port: ${WEB_APP_PORT:8080}

kafkaTopics:
  transactionHistory: ${KAFKA_TOPICS_TRANSACTION_HISTORY:transaction_hist}

services:
  currencyService:
    host: ${CURRENCY_SERVICE_URL:http://localhost:8090}
    getCurrenciesPath: ${CURRENCY_SERVICE_GET_CURRENCY_PATH:/currency/available}
    convertPath: ${CURRENCY_SERVICE_CONVERT_PATH:/rate/convert}
    getCourcePath: ${CURRENCY_SERVICE_GET_COURCE_PATH:/rate/${currencyCode}}
  transactionService:
    host: ${TRANSACTION_SERVICE_HOST:http://localhost:8081}
    createUserPath: ${TRANSACTION_SERVICE_CREATE_USER_PATH:/ts/create}
    getClientDataPath: ${TRANSACTION_SERVICE_GET_CLIENT_DATA_PATH:/ts/{clientId}/data}
    transferPath: ${TRANSACTION_SERVICE_TRANSFER_PATH:/ts/transfer}
    auth:
      username: ${TRANSACTION_SERVICE_AUTH_USERNAME:webservice}
      password: ${TRANSACTION_SERVICE_AUTH_PASS:wbsvc123}

retry:
  maxAttempts: ${RETRY_MAX_ATTEMPTS:4}
  delay: ${RETRY_DELAY:1000}

service:
  mock: false

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}

managed:
  endpoints:
    enabled-by-default: ${MANAGED_ENDPOINTS_ENABLED_BY_DEFAULT:true}
    info:
      enabled: ${MANAGED_ENDPOINTS_INFO_ENABLED:true}


info:
  application:
    name: web-app
    description: Web application of Bank Online
    version: 1.0
