spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: transferGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  profiles:
    active: prod
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:monline
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

user:
  file:
    path: src/main/resources/users/user-data.text

server:
  port: 8080

kafkaTopics:
  transactionHistory: transaction_hist

services:
  currencyService:
    host: http://localhost:8090
    getCurrenciesPath: /currency/available
    convertPath: /rate/convert
    getCourcePath: /rate/${currencyCode}
  transactionService:
    host: http://localhost:8081
    createUserPath: /ts/create
    getClientDataPath: /ts/{clientId}/data
    transferPath: /ts/transfer
    auth:
      username: webservice
      password: wbsvc123

retry:
  maxAttempts: 4
  delay: 1000

service:
  mock: false

logging:
  level:
    root: INFO